name: Azure Static Web Apps CI/CD

pr:
  branches:
     include:
       - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: macOS-latest
  variables:
  - group: Azure-Static-Web-Apps-ambitious-sky-0c1e9da10-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: "e15dc117740c0d788d09932ac633da96da47366ecd8ebbb3a170cf2805bffa9f4-0258d5ec-6d01-40ef-a4c2-7c2c3ed1be64010263913"
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "src" # App source code path
      api_location: "api" # Api source code path - optional
      output_location: "public" # Built app content directory - optional
###### End of Repository/Build Configurations ######

